### ISSUE TITLE
httpx module not loaded from Home Assistant

### ISSUE THREAD

**Issue by gtdiehl** [jesserizzo/envoy_reader#30]
I modified the `manifest.json` file for the Enphase Envoy sensor to point to the latest version of `envoy_reader`

```
-  "requirements": ["envoy_reader==0.11.0"],
+  "requirements": ["envoy_reader==0.16.0"],
```

But when I run Home Assistant, it seems that the `httpx` module is not downloaded.  I don't want to submit a PR against HA to bump the version if I can't get it loaded in my environment first.  

Any ideas?

```
2020-05-04 23:41:08 INFO (SyncWorker_18) [homeassistant.util.package] Attempting install of envoy_reader==0.16.0
...
2020-05-04 23:41:14 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/home/greg/home-assistant/homeassistant/config.py", line 777, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/home/greg/home-assistant/homeassistant/loader.py", line 279, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/greg/home-assistant/homeassistant/components/enphase_envoy/sensor.py", line 4, in <module>
    from envoy_reader.envoy_reader import EnvoyReader
  File "/home/greg/home-assistant/venv/lib/python3.7/site-packages/envoy_reader/envoy_reader.py", line 7, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

**Comment by gtdiehl** [comment]
I see why, the `setup.py` file also has to be updated.  The `requirements.txt` was only updated.  I'll open another PR to update the `setup.py` file.
